import { createContext } from "react";

const sharedCategoryData = {
  fr: {
    categoryLabels: {
      fixation: "Fixation",
      plomberie: "Plomberie",
      outillage: "Outillage",
      electricite: "Electricite",
      peinture: "Peinture",
      securite: "Securite",
    },
    categoryDescriptions: {
      fixation: "Visserie, boulonnerie, chevilles et rondelles.",
      plomberie: "Raccords, vannes, flexibles et accessoires sanitaires.",
      outillage: "Outils manuels et consommables atelier.",
      electricite: "Gaines, dominos, boitiers et accessoires cable.",
      peinture: "Rouleaux, bacs, rubans et preparation surface.",
      securite: "Gants, lunettes, cadenas et equipements chantier.",
    },
  },
  en: {
    categoryLabels: {
      fixation: "Fasteners",
      plomberie: "Plumbing",
      outillage: "Tools",
      electricite: "Electrical",
      peinture: "Painting",
      securite: "Safety",
    },
    categoryDescriptions: {
      fixation: "Screws, bolts, anchors and washers.",
      plomberie: "Fittings, valves, hoses and sanitary accessories.",
      outillage: "Hand tools and workshop consumables.",
      electricite: "Conduits, connectors, boxes and cable accessories.",
      peinture: "Rollers, trays, masking tape and surface preparation.",
      securite: "Gloves, goggles, padlocks and site safety equipment.",
    },
  },
  ar: {
    categoryLabels: {
      fixation: "التثبيت",
      plomberie: "السباكة",
      outillage: "الأدوات",
      electricite: "الكهرباء",
      peinture: "الدهان",
      securite: "السلامة",
    },
    categoryDescriptions: {
      fixation: "براغي، مسامير، مثبتات وحلقات.",
      plomberie: "وصلات، صمامات، خراطيم وإكسسوارات صحية.",
      outillage: "أدوات يدوية ومستلزمات الورشة.",
      electricite: "قنوات، موصلات، علب وإكسسوارات كابلات.",
      peinture: "رولات، أحواض، أشرطة وتحضير الأسطح.",
      securite: "قفازات، نظارات، أقفال ومعدات سلامة الورش.",
    },
  },
};

export const translations = {
  fr: {
    home: "Accueil",
    catalogue: "Catalogue",
    stock: "Stock",
    orders: "Commandes",
    suppliers: "Livraison",
    contact: "Contact",
    professionalHardware: "Quincaillerie Professionnelle",
    heroTitle1: "L'OUTILLAGE",
    heroTitle2: "AU",
    heroTitleAccent: "COEUR",
    heroTitle3: "DU METIER.",
    heroSubtitle:
      "Commandez vos pieces de quincaillerie, demandez un devis et organisez une livraison rapide partout en Tunisie.",
    viewCatalogue: "Voir le catalogue",
    requestQuote: "Demander un devis",
    clientSpace: "Espace Client",
    adminDashboard: "Dashboard Admin",
    featured: "Selection premium",
    featuredTitle1: "PRODUITS",
    featuredTitle2: "EN VEDETTE.",
    seeAll: "Tout voir",
    language: "Langue",
    technicalHardware: "Quincaillerie Technique",
    catalogueTitle: "Catalogue de composants precision",
    catalogueIntro:
      "Systemes de fixation, outillage, plomberie et consommables pour applications professionnelles. Selectionnez vos articles et preparez votre devis.",
    searchPlaceholder: "Rechercher par reference, marque, designation...",
    sortAlpha: "Trier par: Designation (A-Z)",
    sortPriceAsc: "Trier par: Prix croissant",
    sortPriceDesc: "Trier par: Prix decroissant",
    advancedFilters: "Filtres avances",
    brand: "Marque",
    allBrands: "Toutes les marques",
    maxPrice: "Prix max",
    inStockOnly: "En stock seulement",
    reset: "Reinitialiser",
    all: "Tous",
    noProducts: "Aucun composant trouve",
    adjustFilters: "Ajustez vos filtres ou votre recherche pour afficher les articles disponibles.",
    lowStock: "Stock Faible",
    inStock: "En Stock",
    unit: "Unite",
    displayCount: "Affiche",
    on: "sur",
    articles: "articles",
    ...sharedCategoryData.fr,
  },
  en: {
    home: "Home",
    catalogue: "Catalogue",
    stock: "Stock",
    orders: "Orders",
    suppliers: "Delivery",
    contact: "Contact",
    professionalHardware: "Professional Hardware",
    heroTitle1: "TOOLS",
    heroTitle2: "AT THE",
    heroTitleAccent: "HEART",
    heroTitle3: "OF THE TRADE.",
    heroSubtitle:
      "Order hardware parts, request professional quotes and organize fast delivery anywhere in Tunisia.",
    viewCatalogue: "View catalogue",
    requestQuote: "Request a quote",
    clientSpace: "Client Space",
    adminDashboard: "Admin Dashboard",
    featured: "Premium selection",
    featuredTitle1: "FEATURED",
    featuredTitle2: "PRODUCTS.",
    seeAll: "See all",
    language: "Language",
    technicalHardware: "Technical Hardware",
    catalogueTitle: "Precision components catalogue",
    catalogueIntro:
      "Fasteners, tools, plumbing and professional consumables. Select items and prepare your quote request.",
    searchPlaceholder: "Search by reference, brand, designation...",
    sortAlpha: "Sort by: Designation (A-Z)",
    sortPriceAsc: "Sort by: Lowest price",
    sortPriceDesc: "Sort by: Highest price",
    advancedFilters: "Advanced filters",
    brand: "Brand",
    allBrands: "All brands",
    maxPrice: "Max price",
    inStockOnly: "In stock only",
    reset: "Reset",
    all: "All",
    noProducts: "No component found",
    adjustFilters: "Adjust your filters or search query to show available items.",
    lowStock: "Low Stock",
    inStock: "In Stock",
    unit: "Unit",
    displayCount: "Showing",
    on: "of",
    articles: "items",
    ...sharedCategoryData.en,
  },
  ar: {
    home: "الرئيسية",
    catalogue: "الكتالوج",
    stock: "المخزون",
    orders: "الطلبات",
    suppliers: "الموردون",
    contact: "اتصال",
    professionalHardware: "معدات مهنية",
    heroTitle1: "الأدوات",
    heroTitle2: "في",
    heroTitleAccent: "قلب",
    heroTitle3: "المهنة.",
    heroSubtitle:
      "تحكم في المخزون والطلبات والموردين من مكان واحد. مصمم للمهنيين في قطاع البناء.",
    viewCatalogue: "عرض الكتالوج",
    requestQuote: "طلب عرض سعر",
    clientSpace: "مساحة العميل",
    adminDashboard: "لوحة الإدارة",
    featured: "اختيار مميز",
    featuredTitle1: "منتجات",
    featuredTitle2: "مميزة.",
    seeAll: "عرض الكل",
    language: "اللغة",
    technicalHardware: "معدات تقنية",
    catalogueTitle: "كتالوج المكونات الدقيقة",
    catalogueIntro:
      "أنظمة تثبيت وأدوات وسباكة ومستلزمات مهنية. اختر المنتجات وجهز طلب عرض السعر.",
    searchPlaceholder: "ابحث بالمرجع أو العلامة أو الوصف...",
    sortAlpha: "ترتيب حسب: الاسم",
    sortPriceAsc: "ترتيب حسب: السعر الأقل",
    sortPriceDesc: "ترتيب حسب: السعر الأعلى",
    advancedFilters: "فلاتر متقدمة",
    brand: "العلامة",
    allBrands: "كل العلامات",
    maxPrice: "أقصى سعر",
    inStockOnly: "المتوفر فقط",
    reset: "إعادة ضبط",
    all: "الكل",
    noProducts: "لم يتم العثور على منتجات",
    adjustFilters: "عدّل الفلاتر أو البحث لعرض المنتجات المتوفرة.",
    lowStock: "مخزون منخفض",
    inStock: "متوفر",
    unit: "الوحدة",
    displayCount: "عرض",
    on: "من",
    articles: "منتج",
    ...sharedCategoryData.ar,
  },
};

const LanguageContext = createContext({
  language: "fr",
  t: translations.fr,
  toggleLanguage: () => {},
});

export default LanguageContext;
